name: auto-semver-release

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAJOR: "1"               # <- fixed major. change to "2" if I ever push a MAJOR change :3

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Temurin JDKs
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: |
            21
            25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build all versions
        run: ./gradlew :1.21.10:build :26.1:build :26.2:build

      - name: Upload 1.21.10 artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          path: versions/1.21.10/build/libs/*-1.21.10.jar
          archive: false

      - name: Upload 26.1 artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          path: versions/26.1/build/libs/*-26.1.jar
          archive: false

      - name: Upload 26.2 artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          path: versions/26.2/build/libs/*-26.2.jar
          archive: false