name: build-and-release

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: "21"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Temurin JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build (default version from gradle.properties)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: ./gradlew clean build

      - name: Build (tagged release uses tag as version)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          ./gradlew -Pmod_version="$VERSION" clean build

      - name: Upload CI artifact (jars)
        uses: actions/upload-artifact@v4
        with:
          name: jars-${{ github.run_number }}
          path: |
            build/libs/*.jar
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download built jars
        uses: actions/download-artifact@v4
        with:
          name: jars-${{ github.run_number }}
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
